def file(a,name,choice,date,finalprice,discount,quantity):
    file=open(a+".txt","w")
    file.write(str("\n"))
    file.write(str("INVOICE"))
    file.write(str("\n"))
    file.write(str("INVOICE NO." + a))
    file.write(str("\n"))
    file.write(str("Name of Customer " + name))
    file.write(str("\n"))
    file.write(str("Product choosen " + choice))
    file.write(str("\n"))
    file.write(str("Date of purchase " + date))
    file.write(str("\n"))
    file.write("Price of product " + str(finalprice))
    file.write(str("\n"))
    file.write("Discount " + str(discount))
    file.write(str("\n"))
    file.write("Quantity " + str(quantity))
    file.write(str("\n"))
    file.write(str("INVOICE"))
    file.close()

    print("YOUR INVOICE")
    print("INVOICE NO.", a)
    print("Name of Customer ", name)
    print("Product choosen ", choice)
    print("Date of purchase ", date)
    print("Price of product ", finalprice)
    print("Discount ", discount)
    print("Quantity ", quantity)
    print("YOUR INVOICE")
